[package]
name = "fs_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.6", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
structopt = "0.3.21"
prettytable-rs = "^0.10"
thiserror = "1.0.26"
chrono = "0.4.19"
util_macro = {version = "0.1.0", path = "../util_macro"}
fslib = {version="0.1.0", path="../fslib"}
